Fix issue with documentation
I get this error when I copy and paste the text: 
```Error: Error(s) occurred when compiling build script:
E:/dev/code/pmc-orgchart/build.cake(25,45): error CS1503: Argument 2: cannot convert from 'Cake.Common.Tools.DotNetCore.Build.DotNetCoreBuildSettings' to 'Cake.Common.Tools.DotNetCore.Test.DotNetCoreTestSettings'```
And so the change is intended to fix this.